
export const ImageData =[
    {
        id:1,
        imageSrc:'images/img-1.jpg',
        tag:'Events'
    }, 
    {
        id:2,
        imageSrc:'images/img-2.jpg',
        tag:'Ushering'
    },
    {
        id:3,
        imageSrc:'images/img-3.jpg',
        tag:'Hosting'
    },
    {
        id:4,
        imageSrc:'images/img-4.jpg',
        tag:'Events'
    },    {
        id:5,
        imageSrc:'images/img-5.jpg',
        tag:'Ushering'
    },
    {
        id:6,
        imageSrc:'images/img-6.jpg',
        tag:'Events'
    },
    {
        id:7,
        imageSrc:'images/img1.jpg',
        tag:'Ushering'
    },
    {
        id:8,
        imageSrc:'images/img2.jpg',
        tag:'Ushering'
    },
    {
        id:8,
        imageSrc:'images/img3.jpg',
        tag:'Hosting'
    },
    {
        id:9,
        imageSrc:'images/img4.jpg',
        tag:'Hosting'
    },
    {
        id:10,
        imageSrc:'images/img5.jpg',
        tag:'Events'
    },
    {
        id:11,
        imageSrc:'images/img-6.jpg',
        tag:'Ushering'
    },
    {
        id:12,
        imageSrc:'images/img10.jpg',
        tag:'Events'
    },
    {
        id:13,
        imageSrc:'images/img11.jpg',
        tag:'Hosting'
    },
    {
        id:14,
        imageSrc:'images/img12.jpg',
        tag:'Ushering'
    },
    {
        id:15,
        imageSrc:'images/img15.jpg',
        tag:'Hosting'
    }
]